"""empty message

Revision ID: 52e3fc8ee864
Revises: 4801222a6629
Create Date: 2023-03-07 14:25:52.871626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e3fc8ee864'
down_revision = '4801222a6629'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('parent_comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('parent_commment_id', 'comments', ['parent_comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None,naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('parent_commment_id', type_='foreignkey')
        batch_op.drop_column('parent_comment_id')

    # ### end Alembic commands ###
